name: Remote Dispatch Action Initiator

on:
  push

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Edit Deployment file
        run: |
          curl -X POST https://api.github.com/repos/eni-poc/deployment/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
